// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniMes.Api.Shared.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniMes.Api.Shared.Data.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20261002161814_ProductionRuns")]
    partial class ProductionRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniMes.Api.Modules.Carriers.Domain.Carrier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CurrentLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_lot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type_code");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_carrier");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_carrier_code");

                    b.HasIndex("TypeCode", "Status")
                        .HasDatabaseName("ix_carrier_type_code_status");

                    b.ToTable("carrier", "carrier");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Carriers.Domain.CarrierType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<string>("AllowedLotType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("allowed_lot_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_carrier_type");

                    b.ToTable("carrier_type", "carrier");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Equipment.Domain.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CurrentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_run_id");

                    b.Property<int?>("LaneCount")
                        .HasColumnType("integer")
                        .HasColumnName("lane_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforeDown")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_before_down");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_code");

                    b.ToTable("equipment", "eqp");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Execution.Domain.ProductionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<decimal>("GoodQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("good_qty");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<decimal>("RejectQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("reject_qty");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("WorkOrderOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_operation_id");

                    b.HasKey("Id")
                        .HasName("pk_production_run");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_production_run_equipment_id");

                    b.HasIndex("WorkOrderOperationId")
                        .HasDatabaseName("ix_production_run_work_order_operation_id");

                    b.ToTable("production_run", "exec");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Execution.Domain.RunInput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("ConsumedQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("consumed_qty");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_run_input");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_run_input_lot_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_run_input_run_id");

                    b.ToTable("run_input", "exec");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Execution.Domain.RunOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<decimal>("GoodQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("good_qty");

                    b.Property<int?>("Lane")
                        .HasColumnType("integer")
                        .HasColumnName("lane");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<decimal>("RejectQty")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("reject_qty");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id")
                        .HasName("pk_run_output");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_run_output_lot_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_run_output_run_id");

                    b.ToTable("run_output", "exec");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.Domain.GenealogyLink", b =>
                {
                    b.Property<Guid>("ParentLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_lot_id");

                    b.Property<Guid>("ChildLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_lot_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("ParentLotId", "ChildLotId")
                        .HasName("pk_genealogy");

                    b.HasIndex("ChildLotId")
                        .HasDatabaseName("ix_genealogy_child_lot_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_genealogy_run_id");

                    b.ToTable("genealogy", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.Domain.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentCarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_carrier_id");

                    b.Property<Guid?>("CurrentEquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_equipment_id");

                    b.Property<string>("CurrentOperation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("current_operation");

                    b.Property<string>("LotId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("lot_id");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("NextOperation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("next_operation");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("polarity");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("qty");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quality");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uom");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_lot");

                    b.HasIndex("LotId")
                        .IsUnique()
                        .HasDatabaseName("ix_lot_lot_id");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_lot_work_order_id");

                    b.HasIndex("Status", "Type")
                        .HasDatabaseName("ix_lot_status_type");

                    b.ToTable("lot", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.Domain.LotEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("CarrierId")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_id");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<Guid>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("Note")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<decimal?>("Qty")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("qty");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lot_event");

                    b.HasIndex("LotId", "OccurredAt")
                        .HasDatabaseName("ix_lot_event_lot_id_occurred_at");

                    b.ToTable("lot_event", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.Domain.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("polarity");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_material");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_material_code");

                    b.ToTable("material", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.LotIds.IdSequence", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prefix");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer")
                        .HasColumnName("last_value");

                    b.HasKey("Prefix")
                        .HasName("pk_id_sequence");

                    b.ToTable("id_sequence", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.Operation", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("OutputLotType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("output_lot_type");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uom");

                    b.HasKey("Code")
                        .HasName("pk_operation");

                    b.ToTable("operation", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("polarity");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_product_code");

                    b.ToTable("product", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.ProductRouteStep", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.HasKey("ProductId", "Operation")
                        .HasName("pk_product_route");

                    b.HasIndex("Operation")
                        .HasDatabaseName("ix_product_route_operation");

                    b.HasIndex("ProductId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_product_route_product_id_seq");

                    b.ToTable("product_route", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GoodCount")
                        .HasColumnType("integer")
                        .HasColumnName("good_count");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("PlannedEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_end");

                    b.Property<DateTimeOffset>("PlannedStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_start");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforeHold")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_before_hold");

                    b.Property<int>("TargetQty")
                        .HasColumnType("integer")
                        .HasColumnName("target_qty");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_work_order");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_work_order_number");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_work_order_product_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_order_status");

                    b.ToTable("work_order", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.WorkOrderOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.HasKey("Id")
                        .HasName("pk_work_order_operation");

                    b.HasIndex("EquipmentId")
                        .HasDatabaseName("ix_work_order_operation_equipment_id");

                    b.HasIndex("Operation")
                        .HasDatabaseName("ix_work_order_operation_operation");

                    b.HasIndex("WorkOrderId", "Operation")
                        .IsUnique()
                        .HasDatabaseName("ix_work_order_operation_work_order_id_operation");

                    b.ToTable("work_order_operation", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Carriers.Domain.Carrier", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.Carriers.Domain.CarrierType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carrier_carrier_type_type_code");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Execution.Domain.RunInput", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.Execution.Domain.ProductionRun", null)
                        .WithMany("Inputs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_input_production_run_run_id");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Execution.Domain.RunOutput", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.Execution.Domain.ProductionRun", null)
                        .WithMany("Outputs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_output_production_run_run_id");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.ProductRouteStep", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.WorkOrders.Domain.Operation", null)
                        .WithMany()
                        .HasForeignKey("Operation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_route_operation_operation");

                    b.HasOne("MiniMes.Api.Modules.WorkOrders.Domain.Product", null)
                        .WithMany("Route")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_route_product_product_id");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.WorkOrderOperation", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.WorkOrders.Domain.Operation", null)
                        .WithMany()
                        .HasForeignKey("Operation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_operation_operation_operation");

                    b.HasOne("MiniMes.Api.Modules.WorkOrders.Domain.WorkOrder", null)
                        .WithMany("Operations")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_order_operation_work_order_work_order_id");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Execution.Domain.ProductionRun", b =>
                {
                    b.Navigation("Inputs");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.Product", b =>
                {
                    b.Navigation("Route");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.WorkOrder", b =>
                {
                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
