// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniMes.Api.Shared.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniMes.Api.Shared.Data.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20261002154801_IdSequences")]
    partial class IdSequences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniMes.Api.Modules.Carriers.Domain.Carrier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CurrentLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_lot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("type_code");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_carrier");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_carrier_code");

                    b.HasIndex("TypeCode", "Status")
                        .HasDatabaseName("ix_carrier_type_code_status");

                    b.ToTable("carrier", "carrier");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Carriers.Domain.CarrierType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<string>("AllowedLotType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("allowed_lot_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Code")
                        .HasName("pk_carrier_type");

                    b.ToTable("carrier_type", "carrier");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Equipment.Domain.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CurrentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_run_id");

                    b.Property<int?>("LaneCount")
                        .HasColumnType("integer")
                        .HasColumnName("lane_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("StatusBeforeDown")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_before_down");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_code");

                    b.ToTable("equipment", "eqp");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_user_username");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.Domain.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("polarity");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uom");

                    b.HasKey("Id")
                        .HasName("pk_material");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_material_code");

                    b.ToTable("material", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Lots.LotIds.IdSequence", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prefix");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer")
                        .HasColumnName("last_value");

                    b.HasKey("Prefix")
                        .HasName("pk_id_sequence");

                    b.ToTable("id_sequence", "lot");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.Operation", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("OutputLotType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("output_lot_type");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("uom");

                    b.HasKey("Code")
                        .HasName("pk_operation");

                    b.ToTable("operation", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Polarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("polarity");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_product_code");

                    b.ToTable("product", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.ProductRouteStep", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Operation")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("operation");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.HasKey("ProductId", "Operation")
                        .HasName("pk_product_route");

                    b.HasIndex("Operation")
                        .HasDatabaseName("ix_product_route_operation");

                    b.HasIndex("ProductId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ix_product_route_product_id_seq");

                    b.ToTable("product_route", "wo");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.Carriers.Domain.Carrier", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.Carriers.Domain.CarrierType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carrier_carrier_type_type_code");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.ProductRouteStep", b =>
                {
                    b.HasOne("MiniMes.Api.Modules.WorkOrders.Domain.Operation", null)
                        .WithMany()
                        .HasForeignKey("Operation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_route_operation_operation");

                    b.HasOne("MiniMes.Api.Modules.WorkOrders.Domain.Product", null)
                        .WithMany("Route")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_route_product_product_id");
                });

            modelBuilder.Entity("MiniMes.Api.Modules.WorkOrders.Domain.Product", b =>
                {
                    b.Navigation("Route");
                });
#pragma warning restore 612, 618
        }
    }
}
